### ISSUE TITLE
OSB plan

### ISSUE THREAD

**Issue by alexdewar** [djmaxus/matlab-repo-init#8]
This is a rough to-do list based on our kick-off meeting.

General:

- [x] Try using template (@alexdewar and @HarmonicReflux)
- [x] Audit code afterwards
- [ ] ~~Investigate use of `pre-commit` (is it possible to install from Matlab without separate Python installation? Are there any useful Matlab-related hooks?)~~
- [x] #9
- [ ] ~~Investigate viability of using `cookiecutter`/`copier`~~
- [x] #16
- [x] #17
- [x] #19

Documentation:

- [ ] ~~Investigate whether we can create a separate repo for GitHub Pages, to use existing Jekyll workflow~~
- [x] #22
- [x] #23
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15
